pep_version: "2.0.0"
sample_table: sample_table.csv

bioconductor:
  readFunName: readRemoteData
  readFunPath: readRemoteData.R

tprojects:
  - ../target_projects/refdata1/
  - ../target_projects/refdata2/
  - ../
